<a href="https://colab.research.google.com/github/oooinr4018-web/-1/blob/main/ESAA_0904_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#8. 텍스트 분석

(1) NLP(National Language Processing): 머신이 인간의 언어를 이해, 해석

- ex) 기계 번역, 질의응답 시스템

- 머신러닝의 발달: NLP 기술 발전 -> 텍스트 분석 발전

*텍스트 분석: 머신러닝, 언어 이해, 통계 등을 활용한 모델 수립, 정보 추출, 비즈니스 인텔리전스 or 예측 분석 등 수행

(텍스트 분류, 감성 분석, 텍스트 요약, 텍스트 군집화)

(2) 텍스트 마이닝(Text Mining): 비정형 텍스트에서 의미 있는 정보 추출







# 텍스트 분석 이해

텍스트 분석: 비정형 데이터(텍스트) 분석

피처 벡터화(피처 추출): 텍스트를 word 기반의 다수의 피처로 추출하고, 피처에 단어 빈도수와 같은 숫자 값 부여하여, 단어의 조합인 벡터값으로 표현

- 방법: BOW(Bag of Words), Word2Vec

- 피처 벡터화 -> 머신러닝 모델 적용







# 텍스트 분석 수행 프로세스

1. 텍스트 사전 준비작업(텍스트 전처리): 토큰화 작업(클렌징, 대/소문자 변경, 특수문자 삭제 등), 텍스트 정규화 작업(의미 없는 단어 제거 작업, 어근 추출 등)

2. 피처 벡터화/추출: 가공된 텍스트에서 피처 추출, 벡터 값 할당

- 방법: BOW(Count 기반 벡터화, TF-IDF 기반 벡터화), Word2Vec

3. ML 모델 수립 및 학습/예측/평가: 피처 벡터화된 데이터 세트에 적용




# 파이썬 기반의 NLP, 텍스트 분석 패키지

대표적인 파이썬 기반의 NLP, 텍스트 분석 패키지

- NLTK(Natural Language Toolkit for Python)

: 파이썬의 가장 대표적인 NLP 패키지

: 장점 - 방대한 데이터 세트&서브 모듈, 다양한 데이터 세트

(NLP의 모든 영역 커버)

: 단점 - 수행 성능, 정확도, 신기술 엔터프라이즈한 기능 지원 등의 측면에서 부족

- Genism

: 토픽 모델링 분야에서 가장 두각을 나타내는 패키지

: 토픽 모델링을 쉽게 구현할 수 있는 기능 제공

: 다양한 신기능(ex-Word2Vec 구현) 제공

: SpaCy와 가장 많이 사용되는 NLP 패키지

- SpaCy

: 뛰어난 수행 성능

: 많은 NLP 애플리케이션에서 사용

<-> 사이킷런

: 머신러닝 위주의 라이브러리

: 텍스트 분석 기능 수행 가능

(NLP 전용 패키지와 결합하여 애플리케이션 작성)

: 단점 - NLP를 위한 다양한 라이브러리 X




# 텍스트 사전 준비 작업 (텍스트 전처리) - 텍스트 정규화

텍스트 정규화: 텍스트를 머신러닝 알고리즘, NLP 애플리케이션에 입력 데이터로 사용하기 위해 다양한 텍스트 데이터의 사전 작업 수행

1. 클렌징(Cleansing)

: 불필요한 문자, 기호 등 제거

ex) HTML, XML 태그, 특정 기호 등 제거

2. 토큰화(Tokenization)

문장 토큰화: 문장의 마지막을 뜻하는 기호(마침표, 개행문자)에 따라 분리

- sent_tokenize(): 각각의 문장으로 구성된 list 객체 반환





In [5]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

text_sample='The Matrix is everywhere its all around us, here even in this room. \
             You can see it out your window or on your television. \
             You feel it when you go to work, or go to church or pay your taxes.'
sentences=sent_tokenize(text=text_sample)
print(type(sentences), len(sentences))
print(sentences)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


<class 'list'> 3
['The Matrix is everywhere its all around us, here even in this room.', 'You can see it out your window or on your television.', 'You feel it when you go to work, or go to church or pay your taxes.']


단어 토큰화: 문장을 단어로 토큰화

- 공백, 콤마, 마침표, 개행문자 등으로 단어 분리 / 정규 표현식을 이용한 토큰화

- 단어 순서가 중요하지 않은 경우 사용해도 충분

<-> 문장 토큰화: 각 문장이 가지는 시맨틱적인 의미가 중요한 요소인 경우

- word_tokenize(): NTLK에서 기본으로 제공, 단어로 토큰화 작업 수행




In [6]:
from nltk import word_tokenize

sentence="The Matrix is everywhere its all around us, here even in this room."
words=word_tokenize(sentence)
print(type(words), len(words))
print(words)

<class 'list'> 15
['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.']


- sent_tokenize, word_tokenize를 조합하여 모든 단어 토큰화

문서를 문장으로 나누기 -> tokenize_text(): 개별 문장을 단어로 토큰화

In [7]:
from nltk import word_tokenize, sent_tokenize

# 여러 개의 문장으로 된 입력 데이터를 문장별로 단어 토큰화하게 만드는 함수 생성
def tokenize_text(text):

  # 문장별로 분리 토큰
  sentences=sent_tokenize(text)
  # 분리된 문장별 단어 토큰화
  word_tokens=[word_tokenize(sentence) for sentence in sentences]
  return word_tokens

# 여러 문장에 대해 문장별 단어 토큰화 수행.
word_tokens=tokenize_text(text_sample)
print(type(word_tokens), len(word_tokens))
print(word_tokens)

<class 'list'> 3
[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


*n-gram: 연속된 n개의 단어를 하나의 토큰화 단위로 분리

: 문장을 단어별로 하나씩 토큰화 할 경우, 문맥적인 의미가 무시되는 한계 해결

ex) "Agent Smith knocks the door" 2-gram(bigram) 수행

(Agent, Smith), (Smith, knocks), (knocks, the), (the, door)

- 스톱 워드 제거: 의미 없는 단어 제거 전처리 작업

스톱 워드: 분석에 큰 의미가 없는 단어







In [8]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [10]:
print('영어 stop words 개수:', len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

영어 stop words 개수: 198
['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been']


In [12]:
import nltk

stopwords=nltk.corpus.stopwords.words('english')
all_tokens=[]
# 위 예제에서 3개의 문장별로 얻은 word_tokens list에 대해 스톱 워드를 제거하는 반복문
for sentence in word_tokens:
  filtered_words=[]
  # 개별 문장별로 토큰화된 문장 list에 대해 스톱 워드를 제거하는 반복문
  for word in sentence:
    # 소문자로 모두 변환합니다.
    word=word.lower()
    # 토킅화된 개별 단어가 스톱 워드의 단어에 포함되지 않으면 word_tokens에 추가
    if word not in stopwords:
      filtered_words.append(word)
  all_tokens.append(filtered_words)

print(all_tokens)

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'], ['see', 'window', 'television', '.'], ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]


- is, this와 같은 스톱 워드 필터링을 통해 제거



3. Stemming과 Lemmatization: 문법적, 의미적으로 변화하는 단어의 원형 찾기

(1) Stemming:  일반적인 방법 적용(더 단순화된 방법 적용), 원래 단어에서 일부 철자가 훼손된 어근 단어를 추출

(2) Lemmatization: 문법적인 요소, 더 의미적인 부분 감안하여 정확한 철자로 된 어근 단어 추출

*Lemmatization이 Stemming보다 변환이 더 오래 걸림

- NLTK의 다양한 Stemmer 제공

대표 Stemmer: Porter, Lancaster, Snowball Stemmer, Lemmatization을 위한 WordNetMennatizer

'단어'의 Stemming: NTLK에서 필요한 Stemmer 객체(ex- LancasterStemmer()) 생성 -> 객체의 stem('단어') 메서드 호출










In [14]:
from nltk.stem import LancasterStemmer
stemmer=LancasterStemmer()

print(stemmer.stem('working'), stemmer.stem('works'), stemmer.stem('worked'))
print(stemmer.stem('amusing'), stemmer.stem('amuses'), stemmer.stem('amused'))
print(stemmer.stem('happier'), stemmer.stem('happiest'))
print(stemmer.stem('fancier'), stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest
fant fanciest


- work의 진행형, 3인칭 단수, 과거형은 단순한 변화로 원형 단어로 work 제대로 인식

- amus에 변화가 가해진 것으로 인식. amus를 원형 단어로 인식

- happy, fancy의 비교형, 최상급형으로 변형된 단어의 정확한 원형 인식 X

In [16]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

lemma=WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'), lemma.lemmatize('amuses', 'v'), lemma.lemmatize('amused', 'v'))
print(lemma.lemmatize('happier', 'a'), lemma.lemmatize('hapiest', 'a'))
print(lemma.lemmatize('fancier', 'a'), lemma.lemmatize('fanciest', 'a'))

amuse amuse amuse
happy hapiest
fancy fancy


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


- WordNetLemmatizer를 이용한 Lemmatization  수행

- 단어의 '품사' 입력

ex) 동사 = 'v', 형용사= 'a'로 입력

# Bag of Words - BOW

Bag of Words: 문서가 가지는 모든 단어의 문맥, 순서 무시하고 빈도 값을 부여해 피처 값을 추출하는 모델

- 장점: 쉽고 빠른 구축

(개별 문장에서 해당 단어가 나타나는 횟수를 각 단어에 기재하여 비교)

- 단점: 문맥 의미 반영 부족, 희소 행렬 문제

*희소 행렬: 대부분의 값이 0으로 채워지는 행렬

*밀집 행렬: 대부분의 값이 0이 아닌 의미 있는 값으로 채워진 행렬

BOW 피처 벡터화

: 숫자형 피처를 데이터로 입력받는 머신러닝 알고리즘

(텍스트를 숫자형 값인 벡터 값으로 변환하는 과정 필요)

: M개의 텍스트 문서, 각각 N개의 단어

-> M X N개의 단어 피처로 이루어진 행렬 구성

- 카운트 기반의 벡터화

: 단어 피처에 값을 부여할 때 각 문서에서 해당 단어가 나타는 횟수

: 카운트 값이 높을수록 중요한 단어로 인식

- TF-IDF 기반의 벡터화

: 개별 문서에서 자주 나타나는 단어에 높은 가중치 부여,

모든 문서에서 전반적으로 자주 나타나는 단어에 페널티 부여

ex) '분쟁', '종교 대립', '유혈 사태' - 높은 가중치

'많은', '빈번하게', '당연히' - 패널티 부여


# 사이킷런의 Count 및 TF-IDF 벡터화 구현: CountVectorizer, TfidfVectorizer

1. 사이킷런의 CountVectorizer 클래스

: 카운트 기반의 벡터화를 구현한 클래스

: 피처 벡터화 + 텍스트 전처리(소문자 일괄 변환, 토큰화, 스톱 워드 필터링 등)

: 입력 파라미터 설정하여 수행

- max_df: 높은 빈도수를 가지는 단어가 스톱 워드와 비슷한 문법적인 특성을 가진 반복 단어일 가능성이 높기에 제거하기 위해 사용

- min_df: 적은 빈도수를 가지는 단어는 크게 중요 X, 가비지성 단어일 가능성이 높기에 제외하기 위해 사용

- max_features: 추출하는 피처의 개수를 제한하여 피처 추출

- stop_words: 스톱 워드로 지정된 단어는 추출에서 제외

- n_gram_range: 단어를 (범위 최솟값, 범위 최댓값)으로 토큰화된 단어를 묶어서 피처로 추출

- analyzer: 피처 추출을 수행한 단위 지정

(디폴트 'word')

- token_pattern: 토큰화를 수행하는 정규 표현식 패턴 지정

- tokenizer: 토큰화를 별도의 커스텀 함수로 이용시 적용

: fit(), transform()을 통한 피처 벡터화된 객체 반환

: 사전 데이터 가공(모든 문자 소문자로 변환) -> 토큰화(디폴트는 단어 기준, n_gram_range 반영) -> 텍스트 정규화(Stop Words 필터링 수행 / Stemmer, Lemmatize는 CountVectorizer에서 지원 X) -> 피처 벡터화(max_df, min_df, max_features 등의 파라미터 반영)






# BOW 벡터화를 위한 희소 행렬

피처 벡터화된 희소 행렬의 형태

희소 행렬: 대규모 행렬의 대부분의 값을 0이 차지하는 행렬

(BOW 형태를 가진 언어 모델의 피처 벡터화의 대부분이 희소 행렬)

: 너무 많은 불필요한 0 값이 메모리 공간에 할당, 행렬 크기가 커서 많은 시간 소모

-> 적은 메모리 공간 차지 가능 변환

- 방법1: COO 형식

- 방법2: CSR 형식

1. COO 형식

: 0이 아닌 데이터만 별도의 데이터 배열(Array)에 저장, 그 데이터가 가리키는 행&열의 위치를 별도의 배열로 저장하는 방식

ex) [[3, 0, 1], [0,2,0]]

0이 아닌 데이터: [3, 1, 2]

0이 아닌 데이터가 있는 위치 (row, col): (0,0), (0,2), (1,1)

(별도의 배열 row [0,0,1], column [0,2,1])

: 사이파이(Scipy)의 sparse 패키지를 이용한 희소 행렬 변환

넘파이의 ndarray 객체로 만들기 -> COO 형식의 희소 행렬로 변환 (-> toarray() 메서드로 밀집 형태 행렬 출력(원래 데이터 형태))



In [18]:
import numpy as np

dense=np.array([[3,0,1],[0,2,0]])

from scipy import sparse

# 0이 아닌 데이터 추출
data=np.array([3,1,2])

# 행 위치와 열 위치를 각각 배열로 생성
row_pos=np.array([0,0,1])
col_pos=np.array([0,2,1])

# sparse 패키지의 coo_matrix를 이용해 COO 형식으로 희소 행렬 생성
sparse_coo=sparse.coo_matrix((data,(row_pos, col_pos)))

In [19]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

2. CSR 형식

: 행 위치 배열 내에 있는 고유한 값의 시작 위치만 다시 별도의 위치 배열로 가지는 변환 방식 + 마지막에 데이터의 총 항목 개수 배열에 추가

:COO 형식의 행&열 위치 나타내는 위치 데이터 반복 사용 문제점 해결 (적은 메모리, 빠른 연산)

ex) 행 위치 배열 [0,0,1,1,1,1,1,2,2,3,4,4,5]를 CSR로 변환 -> [0,2,7,9,10,12, 13]

: 사이파이의 csr_matrix 클래스 이용

(csr_matrix 생성 파라미터: 0이 아닌 데이터 배열, 열 위치 배열, 행 위치 배열의 고유한 값의 시작 위치 배열)





In [21]:
from scipy import sparse
dense2=np.array([[0, 0, 1, 0, 0, 5],
                 [1, 4, 0, 3, 2, 5],
                 [0, 6, 0, 3, 0, 0],
                 [2, 0, 0, 0, 0, 0],
                 [0, 0, 0, 7, 0, 8],
                 [1, 0, 0, 0, 0, 0]])

# 0이 아닌 데이터 추출
data2=np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행 위치와 열 위치를 각각 array로 생성
row_pos=np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos=np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환
sparse_coo=sparse.coo_matrix((data2, (row_pos, col_pos)))

# 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성
row_pos_ind=np.array([0, 2, 7, 9, 10, 12, 13])

# CSR 형식으로 변환
sparse_csr=sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


- COO, CSR를 통해 희소 행렬의 메모리를 줄일 수 있음.

- 실제 사용 시, 밀집 행렬을 생성 파라미터로 입력하면, COO, CSR 희소 행렬 생성

- 사이킷런의 CountVectorizer, TfidVectorizer 클래스로 변환된 피처 벡터화 행렬 = 사이파이의 CSR 형태의 희소 행렬



In [22]:
dense3=np.array([[0, 0, 1, 0, 0, 5],
                 [1, 4, 0, 3, 2, 5],
                 [0, 6, 0, 3, 0, 0],
                 [2, 0, 0, 0, 0, 0],
                 [1, 0, 0, 0, 0, 0]])

coo=sparse.coo_matrix(dense3)
csr=sparse.csr_matrix(dense3)