<a href="https://colab.research.google.com/github/oooinr4018-web/-1/blob/main/ESAA_0921_%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

p.584-p.601

# Chapter09. 추천 시스템

# 추천 시스템의 개요

- 추천 콘텐츠 대부분은 개인적 취향을 정확히 이해, 추천

- 선택된 콘텐츠, 연관 추천 콘텐츠가 얼마나 사용자의 관심을 끄는지, 개인 맞춤 콘텐츠를 추천했는지 -> 사이트의 평판 좌우

- 추천 시스템을 통해 사용자의 취향을 시스템이 발견하고, 그에 맞는 콘텐츠 추천

- 많은 데이터가 축적되면서 더 정확한 추천 (선순환 시스템)

# 온라인 스토어의 필수 요소, 추천 시스템

- 다양한 상품 이미지, 번잡한 카테고리, 메뉴 구성 등으로 인한 제품 선택의 어려움

-> 부정적 이미지, 매출 감소

--> 추천 시스템이 해결

- 데이터: 사용자의 구매 상품, 사용자가 둘러보거나 장바구니에 넣은 상품, 사용자의 제품 평가, 사용자의 취향, 사용자가 클릭한 것들







# 01.추천 시스템의 유형

1. 콘텐츠 기반 필터링 (Content based filtering)

2. 협업 필터링 (Collaborative filtering)

- 최근접 이웃 (Nearest Neighbor) 협업 필터링

- 잠재 요인 (Latent Factor) 협업 필터링




콘텐츠 기반 필터링 + 최근접 이웃 기반 협업 필터링 -> 잠재 요인 협업 필터링 기반 추천 시스템-> 하이브리드 형식(콘텐츠 기반 + 협업 기반)

(아마존: 아이템 기반의 최근접 이웃 협업 필터링 방식)





# 02. 콘텐츠 기반 필터링 추천 시스템

콘텐츠 기반 필터링 방식: 사용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 코넨츠를 가진 다른 아이템 추천하는 방식

ex) 영화 '컨택트', 영화 '블레이드 러너 2049', 영화 '프로메테우스'

-> 사용자 선호 프로파일

- 선호 장르: SF, 액션, 스릴러

- 선호 배우: 에이미 아담스, 마이클 패스벤터 등

- 선호 감독: 리들리 스콧, 드니 빌뇌브

# 03. 최근접 이웃 협업 필터링

협업 필터링 방식: 사용자가 아이템에 매긴 평점 정보, 상품 구매 이력과 같은 사용자 행동 양식만을 기반으로 추천 수행 / 사용자가 평가한 다른 아이템을 기반으로 사용자가 평가하지 않은 아이템의 예측 평가 도출

1. 목표: 축적된 사용자 행동 데이터를 기반으로 사용자가 아직 평가하지 않은 아이템을 예측 평가

2. 사용자-아이템 평점 행렬 데이터에 의지하여 추천 수행

- 행: 개별 사용자, 열: 개별 아이템 - 사용자 아이디 행, 아이템 아이디 열 위치 해당 값이 평점을 나타내는 형태

- 데이터가 레코드 레벨 형태라면, 판다스의 pivot_table() 함수를 이용하여 평점 행렬 형태로 변경

- 사용자-아이템 평점 행렬은 희소 행렬의 특성 (평점을 매기지 않는 사용자들)

3. 최근접 이웃 협업 필터링 = 메모리 협업 필터링

4. 유형

(1) 사용자 기반(User-User) 최근접 이웃 협업 필터링

- 특정 사용자와 유사한 다른 사용자를 Top-N으로 선정하여, Top-N 사용자가 좋아하는 아이템을 추천하는 방식

- 특정 사용자, 타 사용자 간의 유사도(Similarity) 측정

-> 유사도가 높은 Top-N 사용자 추출하여 그들이 선호하는 아이템 추천

(2) 아이템 기반(item-item) 최근접 이웃 협업 필터링

- 추천 기준: 사용자들이 해당 아이템을 좋아하는지/싫어하는지의 평가 척도

(아이템의 속성과 관련 X)

- 사용자 기반 협업 필터링보다 높은 정확도

- 대부분 아이템 기반 알고리즘 적용










- 추천 시스템의 유사도 측정 방법: 코사인 유사도

- 추천 시스템에 사용되: 다차원 희소 행렬 (피처 벡터화된 텍스트 데이터와 동일)


# 04. 잠재 요인 협업 필터링

잠재 요인 협업 필터링: 사용자-아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출하여 추천 예측을 할 수 있게 하는 기법

- 행렬 분해: 차원 감소 기법(ex-SVD)으로 대규모 다차원 행렬을 분해하는 과정에서 잠재 요인 추출 (다차원 행렬 -> 저차원 행렬)

- 사용자-아이템 행렬 데이터 (다차원) -> 사용자-잠재 요인 행렬 + 잠재 요인-아이템 행렬(전치 행렬) (저차원)

ex) 사용자-잠재 요인 행렬: 사용자의 영화 장르에 대한 선호도

아이템-잠재 요인 행렬: 영화의 장르별 특성값

- 분해된 두 행렬의 내적 -> 새로운 예측 사용자-아이템 평점 행렬 데이터 (평점을 부여하지 않은 아이템에 대한 예측 평점 도출)

ex) 사용자-아이템 평점 행렬 R(u,i) (u: 사용자 아이디, i: 아이템 아이디)

사용자-잠재 요인 행렬 P(u,k) (u: 사용자 아이디, k: 잠재 요인 (장르별 선호도))

factor 1: 액션 선호도

factor 2: 로맨스 선호도

영화의 장르별 요소 향렬 Q(i,k) (i: 아이템 아이디, k: 잠재 요인 (장르별 요소))

Q.T: Q의 행, 열 위치 교환 행렬

평점: 사용자의 장르별 선호도 벡터, 영화의 장르별 특성 벡터의 곱

R(1,1)의 값 = P 행렬의 User1 벡터 * Q.T 행렬의 item1 벡터

R(1,2)의 값 = P 행렬의 User1 벡터 * Q.T 행렬의 item2 벡터











# 행렬 분해의 이해

대표 기법: SVD(Singular Vector Decomposition), NMF(Non-Negative Matrix Factorization)

- 평점 행렬 R(MxN 차원) = 사용자-K 차원 잠재 요인 행렬 P(MxK) + K 차원 잠재 요인-아이템 행렬 Q.T(KxN) (행렬 분해)

(R=P*Q.T)

- ex) r(2,4)(R 행렬의 2행 사용자, 4열 아이템 해당 평점) = p2 * q4(t)

- ex) r(2,3)(R 행렬의 2행 사용자, 3열 아이템 해당 평점, 미정 데이터) = p2 * q3(t)

- 사용자-아이템 평점 행렬의 미정 값을 포함한 모든 평점 값은, P 행렬과 Q.T 행렬의 내적을 통해 계산 가능

- SVD는 NaN 값이 없는 행렬에만 적용 가능

- R 행렬은 많은 NaN 값을 가지므로, SVD 방식으로 P 행렬과 Q 행렬로 분해 불가

-> 확률적 경사 하강법(SGD), ALS 방식으로 SVD 수행


# 확률적 경사 하강법을 이용한 행렬 분해

확률적 경사 하강법을 이용한 행렬 분해 방법: P, Q 행렬로 계산된 예측 R 행렬 값이 실제 R 행렬 값과 가장 최소의 오류를 가질 수 있도록 반복적인 비용 함수 최적화를 통해 P, Q를 유추해내는 것

방법:

1. P, Q를 임의의 값을 가진 행렬로 설정

2. P와 A.T를 곱해 예측 R 행렬 계산 -> 예측 R 행렬과 실제 R 행렬에 해당하는 오류 값 계산

3. 2에서 계산된 오류 값을 최소화할 수 있도록 P, Q 행렬을 적절한 값으로 업데이트

4. 만족할 만한 오류 값을 가질 때까지, 2번+3번을 반복하며 P와 Q 값 업데이트하며 근사화

비용 함수식 = min(Sigma(r(u,i)-puqi(t))^2 + 람다 * (||qi||^2+||pu||^2)

pu'(업데이트 값) = pu + 에타 * (e(u,i) * qi - 람다 * pu)

qi'(업데이트 값) = qi + 에타 * (e(u,i) * pu - 람다 * qi)

(에타: SGD 학습률, 람다: L2 규제 계수 (과적합 방지용))



SGD 기반 행렬 분해: L2 규제를 반영해 실제 R 행렬 값과 예측 R 행렬 값의 차이를 최소화하는 방향으로, P행렬과 Q행렬에 업데이트를 반복 수행하며, 최적화된 예측 R 행렬을 구하는 방식

In [2]:
# SGD 기반 행렬 분해
# 원본 행렬 R을 P와 Q로 분해 후, P와 Q.T의 내적으로 예측 행렬 생성
# 원본 행렬 R을 np.NaN을 포함하여 생성
# P와 Q는 정규 분포를 가진 랜덤 값으로 초기화
# 잠재 요인 차원 = 3

import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정.
R=np.array([[4, np.nan, np.nan, 2, np.nan],
            [np.nan, 5, np.nan, 3, 1],
            [np.nan, np.nan, 3, 4, 4],
            [5, 2, 1, 2, np.nan]])
num_users, num_items=R.shape
K=3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력합니다.
np.random.seed(1)
P=np.random.normal(scale=1./K, size=(num_users, K))
Q=np.random.normal(scale=1./K, size=(num_items, K))

In [3]:
# 실제 R 행렬과 예측 행렬의 오차를 구하는 get_rmse() 함수
# 실제 R 행렬의 널이 아닌 행렬 값의 위치 인덱스 추출
# 해당 인덱스에 있는 실제 R 행렬 값, 분해된 P, Q -> 예측 행렬 값의 RMSE 값 반환

from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
  error=0
  # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
  full_pred_matrix=np.dot(P, Q.T)

  # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스를 추출하여 실제 R 행렬과 예측 행렬의 RMSE 추출
  x_non_zero_ind=[non_zero[0] for non_zero in non_zeros]
  y_non_zero_ind=[non_zero[1] for non_zero in non_zeros]
  R_non_zeros=R[x_non_zero_ind, y_non_zero_ind]
  full_pred_matrix_non_zeros=full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
  mse=mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
  rmse=np.sqrt(mse)

  return rmse

In [5]:
# SGD 기반 행렬 분해
# 1. R에서 널 값 제외한 데이터의 행렬 인덱스 추출
# steps: SGD를 반복해서 업데이트할 횟수 # learning_rate: SGD 학습률 # r_lambda: L2 Regularization 계수
# steps=1000 반복하면서, pu, qi 값 업데이트 (pu'=pu + eta * (e(u,i) * qi - 람다 * pu, qi'=qi + eta * (e(u,i) * pu - 람다 *qi)
# get_rmse() 함수로 50회 반복할 때마다 오류 값 출력

# R>0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장.
non_zeros=[ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]

steps=1000
learning_rate=0.01
r_lambda=0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트.
for step in range(steps):
  for i, j, r in non_zeros:
    # 실제 값과 예측 값의 차이인 오류 값 구함
    eij=r-np.dot(P[i,:], Q[j,:].T)
    # Regulatrization을 반영한 SGD 업데이트 공식 적용
    P[i,:]=P[i,:]+learning_rate*(eij*Q[j,:]-r_lambda*P[i,:])
    Q[j,:]=Q[j,:]+learning_rate*(eij*P[i,:]-r_lambda*Q[j,:])

    rmse=get_rmse(R, P, Q, non_zeros)
    if(step%50)==0:
      print("### iteration step: ", step, "rmse :", rmse)


### iteration step:  0 rmse : 3.259459570920174
### iteration step:  0 rmse : 3.2585295271131973
### iteration step:  0 rmse : 3.2521099280637533
### iteration step:  0 rmse : 3.250301384821969
### iteration step:  0 rmse : 3.2504784118719807
### iteration step:  0 rmse : 3.2492149633392726
### iteration step:  0 rmse : 3.247385782225293
### iteration step:  0 rmse : 3.245556255980146
### iteration step:  0 rmse : 3.2401598629557324
### iteration step:  0 rmse : 3.2382931118523164
### iteration step:  0 rmse : 3.238413055138202
### iteration step:  0 rmse : 3.2370465747107744
### iteration step:  50 rmse : 0.5015004152105822
### iteration step:  50 rmse : 0.5013163339724306
### iteration step:  50 rmse : 0.5001971542619058
### iteration step:  50 rmse : 0.5000256311100154
### iteration step:  50 rmse : 0.5001282058216056
### iteration step:  50 rmse : 0.4994928628629658
### iteration step:  50 rmse : 0.49959027043603593
### iteration step:  50 rmse : 0.49910871647594846
### iteration s

In [8]:
# 분해된 P와 Q 함수를 P*Q.T로 예측 행렬을 생성하여 출력

pred_matrix=np.dot(P, Q.T)
print('예측 행렬: \n', np.round(pred_matrix, 3))

예측 행렬: 
 [[3.99  0.783 1.341 2.003 1.729]
 [6.702 4.978 0.953 2.98  1.003]
 [6.933 0.42  2.987 3.976 3.986]
 [4.968 2.005 1.007 2.018 1.163]]


- 예측 행렬과 원본 행렬의 널이 아닌 값은 큰 차이 X

- 예측 행렬의 널 값은 새로운 예측값

- 후에, 사용자-영화 평점 행렬을 행렬 분해하여 영화 추천 로직 구현 예정